name: Feature request
description: Suggest an idea or improvement
title: 'feat: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      placeholder: I find it hard to...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other ways to solve this could be...

  - type: input
    id: url
    attributes:
      label: Share link (optional)
      description: If relevant, include a share link demonstrating the current behavior.
      placeholder: https://...
